### ISSUE TITLE
override default NimblePool checkout timeout

### ISSUE THREAD

**Issue by dvic** [bitcrowd/chromic_pdf#149]
Should we allow users to override the default timeout of 5 seconds for `NimblePool.checkout/4`? It seems like there's now way to do this currently (we still sometimes have some ci failing because of this now 🙂 )

**Comment by maltoe** [comment]
Guess you can give it a try :shrug: 

Not sure if it'll help though, it sounds a bit like you have a more general issue with your CI setup? Are you just trying to print a whole lot of PDFs in parallel? If so, increasing the number of sessions to spawn would probably help. Or maybe add a work queue and simply assert that a print job has been added?

In the end, ChromicPDF's session pool was never designed to function as a queue. In other words: If you want to print 6 PDFs in parallel with 5 workers, it by design should error on the 6th PDF (minus the allowed 5s checkout timeout). The sole purpose of the pool is to provide (bounded) parallelism.

**Comment by maltoe** [comment]
Or another idea: Spawn a chromic process in the test (ExUnit's `start_supervised`) and inject the chromic instance to use into the test (via process dict, for instance). That way you would simply start another browser for each test that wants to print a PDF.

**Comment by dvic** [comment]
> Not sure if it'll help though, it sounds a bit like you have a more general issue with your CI setup? Are you just trying to print a whole lot of PDFs in parallel? If so, increasing the number of sessions to spawn would probably help.

This did help actually, thanks! Also, I've removed `async: true` from the tests that use ChromicPDF, which results in having more cpu available when the tests run.

> In the end, ChromicPDF's session pool was never designed to function as a queue. In other words: If you want to print 6 PDFs in parallel with 5 workers, it by design should error on the 6th PDF (minus the allowed 5s checkout timeout). If you want to queue work up, you need to add a queue (e.g. Oban). The sole purpose of the pool is to provide (bounded) parallelism.

Makes sense!

> Or another idea: Spawn a chromic process in the test (ExUnit's start_supervised) and inject the chromic instance to use into the test unit (via process dict, for instance). That way you would simply start another browser for each test that wants to print a PDF.

I'll keep this in mind if the problem pop-ups again. Thanks!
