### ISSUE TITLE
Cleanly handle page overflow of a `<table>`

### ISSUE THREAD

**Issue by RealVidy** [bitcrowd/chromic_pdf#150]
I am generating a pdf with a long table that often overflows into a second page and I am not sure how I should go about making the transition clean. Ideally, my table would be cut where a new `th` header starts.

Is this something I can do?

![image](https://user-images.githubusercontent.com/1413803/163032192-2a334217-97fc-4b39-9656-2d4b32f958de.png)

**Comment by maltoe** [comment]
Hey @RealVidy 

No, I'm afraid not. Not that I know of, at least. You can give it a `page-break-inside: avoid;`, but if it's truly so long that it has to be broken inside, there's not much that Chrome can do for it. Chrome will repeat only table headers for you (see for instance the print dialog on https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population), but since these are "in-between" `th`s, I don't think it can do anything.

I'd try the following options in your scenario:

* Can you maybe break up the table in markup of `<div>` sections?
* Otherwise maybe [Paged.js](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population) can help you, though I haven't used it myself so far.

**Comment by RealVidy** [comment]
Thanks @maltoe, I'll try the `<div>` sections instead of the table. I'll close this issue in the mean time.

I did look into Paged.js but it is so much simpler to use an elixir lib for my use case that I am going to push through with chromic_pdf :) Thanks for your work here!

**Comment by maltoe** [comment]
IIRC someone has tried using paged.js _within_ ChromicPDF at some point, i.e. using just the client-side JS potion of it, but not the puppeteer integration. Not sure how that turned out though.
