### ISSUE TITLE
Timeout error on shutting down

### ISSUE THREAD

**Issue by atavistock** [bitcrowd/chromic_pdf#171]
Running a deploy on fly.io with _zero_ activity and no pdfs being generated.  I'm unsure if this is from the pool shutting down or starting up.

```
	 00:19:00.549 [error] Task #PID<0.510.0> started from #PID<0.509.0> terminating
	 ** (RuntimeError) Timeout in Channel.run_protocol/3!
	 The underlying GenServer.call/3 exited with a timeout. This happens when the browser was
	 not able to complete the current operation (= PDF print job) within the configured
	 5000 milliseconds.
	 If you are printing large PDFs and expect long processing times, please consult the
	 documentation for the `timeout` option of the session pool.
	 If you are *not* printing large PDFs but your print jobs still time out, this is likely a
	 bug in ChromicPDF. Please open an issue on the issue tracker.
	     (chromic_pdf 1.3.0) lib/chromic_pdf/pdf/browser/channel.ex:26: ChromicPDF.Browser.Channel.run_protocol/3
	     (chromic_pdf 1.3.0) lib/chromic_pdf/pdf/browser/session_pool.ex:122: ChromicPDF.Browser.SessionPool.do_init_worker/3
	     (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
	     (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
	     (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
	 Function: #Function<0.72123262/0 in ChromicPDF.Browser.SessionPool.init_worker/1>
	     Args: [
```

**Comment by maltoe** [comment]
Hello @atavistock,

this looks like it fails while starting up (`ChromicPDF.Browser.SessionPool.do_init_worker/3`). When ChromicPDF is started as part of your supervision tree, it launches a headless chrome/chromium OS process and proceeds to spawn a pool of "targets" (= tabs) in it. This is what you see here, the `SessionPool` failing to spawn a target due to a timeout.

Could you try launching with the `discard_stderr: false` option and see if the browser spits out any errors?

**Comment by maltoe** [comment]
Hey @atavistock 

I'm going to assume you got it working in the end (or move on somewhere else) and will close this for now. Feel free to re-open if this is still an issue for you.
