### ISSUE TITLE
No accessibility tags in Ghostscript-generated files

### ISSUE THREAD

**Issue by MaeIsBad** [bitcrowd/chromic_pdf#207]
Hey! Sorry for not taking a look at this when the PR was originally in review but there are a few things you should know related to merging chromic_pdf generated documents with ghostscript:

- it's really slow. To quote an ex-coworker
> In my testing, I found that, with a large PDF file (~200 pages), GhostScript took 12 seconds to handle the request, and pdfunite took... 4.47 seconds! This should therefore speed up merging PDFs significantly. Turns out, ghostscript is a significant and slow bottleneck.

- it removes the accessibility annotations added via `--export-tagged-pdf`. This seems like something that you don't want happening implicitly
https://github.com/bitcrowd/chromic_pdf/blob/f8d7a391f649b861579b6432041d04ea512e0546/lib/chromic_pdf/pdf/chrome_runner.ex#L109

**Comment by maltoe** [comment]
Hey @MaeIsBad 

thank you for your comments. I was unaware of the issue that Ghostscript is slow to join multiple PDFs, though am not surprised. But the factor 2  (in comparison to a specialized tool like pdfunite) you mention and also the 12s / 200 pages measurement don't seem excessive to me, so I would guess that for most users this is not a big deal in reality.

I'm aware that Ghostscript drops all structural information from a source PDF when writing to its `pdfwrite` output device, unfortunately. This also affects the PDF/A conversion. In our own apps, accessibility of the generated files (mostly invoice documents or the like) has never been a priority - not saying we wouldn't prefer files to keep their structural information, only that PDF/A features like fixed presentation are more critical to us. IOW, since (luckily) we need `PDF/A-3b` compliance only, not `-3a`, we didn't really bother looking into this topic.

According to [internet wisdom](https://stackoverflow.com/q/69299263), Ghostscript is not capable of transferring these annotations from input documents to the output, as in, `pdfwrite` can write pdfmarks perfectly fine, only they're not forwarded from the PDF interpreter. I personally wonder if this is going to change with [their new PDF interpreter](https://ghostscript.com/blog/pdfi.html), but haven't had the time to look into this yet.

As a follow-up, I'd suggest we:

- Improve the documentation:
  - the "Multiple Sources" section of `print_to_pdf/2` should clearly mention that Ghostscript removes tags, and that the user should use other tools if accessibility of the files is a requirement
    -  btw, `pdfunite` also doesn't retain the tags, so I don't know any tool that does, atm
  - maybe mention that GS is not the fastest of all tools, though my personal gutfeel here is to leave out this information to not scare people away
  - Mention the part about removal of tags for `print_to_pdfa/2` and `convert_to_pdfa/2`, too, if it isn't already.
- Later, if people realize performance is critical to them, we could add an option like `:join_with` or so to make the join mechanism configurable

**Comment by maltoe** [comment]
@MaeIsBad feel free to review #208 :pray:

**Comment by maltoe** [comment]
@MaeIsBad Thanks again, also for the review! :purple_circle: 

IMO the docs address this adequately now, and I'd now wait for other people to come and ask for a non-ghostscript merge feature. Closing this issue.
