### ISSUE TITLE
GPU renderer on a headless server?

### ISSUE THREAD

**Issue by silverdr** [bitcrowd/chromic_pdf#236]
When starting Phx Application with ChromicPDF I get some errors out in the logs. The one that I think is closely related to way Chrome is started:
```
[0308/135155.636929:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is [...]
```
but there are other about dbus and  co.

Then I see three Chrome (chromium) processes, with conflicting arguments like:
```
chromium --show-component-extension-options --enable-gpu-rasterization --no-default-browser-check [...] --disable-gpu [...]
```
and another one: 
```
chromium --type=gpu-process --no-sandbox --disable-breakpad --enable-gpu-rasterization --headless --ozone-platform=headless --use-angle=swiftshader-webgl --headless --gpu-preferences=[]...]
```
Any quick fixes to those?

**Comment by maltoe** [comment]
Hi @silverdr 

I'm having trouble to give you any "quick fixes" without a description of what doesn't work as expected.

Regardless, here are a few remarks/observations on your statements:

- Since you're seeing the Chrome logs in your Phoenix logs/console, I assume you have set `discard_stderr: false`, right?
- Chrome spits out a lot of warnings and even `ERROR` lines at launch, most of which you can ignore. I'm also wondering why so much noise comes from `gpu_init.cc` even though we pass the `--disable-gpu` flag, but Chrome is a beast and who are we to judge its implementation :shrug:
- A running Chrome instance consists of multiple OS processes, at least one master and three or four helper processes, plus one "renderer" process per tab. You can find out which one is the master by looking for the absence of a `--type` option.
- The "conflicting arguments" you found are indeed striking, but also not unusual. A lot of distributions wrap the chrome binary in a wrapper script (e.g. `/usr/bin/chromium-browser` on Alpine is a script executing `/usr/lib/chromium/chrome` and adding some params like `--extra-plugin-dir`). In your case, the `--enable-gpu-rasterization` is not added by ChromicPDF, and seems to conflict with `--disable-gpu`, but I'd suggest you ignore this as long as you can print PDFs. You can review the list of flags we pass to Chrome [here](https://github.com/bitcrowd/chromic_pdf/blob/9676c1244ab6f79662f2579d3de1272af79f9097/lib/chromic_pdf/pdf/chrome_runner.ex#L86), by the way.

Hope this helps.

Best,
malte

**Comment by silverdr** [comment]
Thank you for your response.

> Since you're seeing the Chrome logs in your Phoenix logs/console, I assume you have set discard_stderr: false, right?

Correct.

It looked like the "master" process got those extra flag(s) from your invocation and since some GPU related features are enabled there (despite `--disable-gpu`), it spawns children like `type=gpu-process` and Co. dropping out errors. So my hope for quick fix was in double-checking the arguments/flags you pass when starting Chrome. Since you say those do not come from you I shall have to double-check whether the invoked command isn't in fact a wrapper script or something.

TNX
