### ISSUE TITLE
websocket_debugger_url failing on windows erlang26/elixir15.7

### ISSUE THREAD

**Issue by joshamb** [bitcrowd/chromic_pdf#286]
### My setup:
- OS: Windows Server 2019
- Erlang: 26.1.2
- Elixir: 15.7
- Chrome: Version 120.0.6099.71 (Official Build) (64-bit)
- chromic_pdf: latest from main

### Issue:

When running `mix test test\integration\inet_connection_test.exs`, I get the following error:

```elixir
  1) test connecting to Chrome via network :chrome_address: option spawns the Inet connection process (ChromicPDF.InetConnectionTest)
     test/integration/inet_connection_test.exs:33
     ** (RuntimeError) failed to start child with the spec {ChromicPDF, [chrome_address: {"localhost", 29222}]}.
     Reason: shutdown: failed to start child: ChromicPDF.Browser
         ** (EXIT) shutdown: failed to start child: ChromicPDF.Browser.Channel
             ** (EXIT) an exception was raised:
                 ** (ChromicPDF.Connection.ConnectionLostError) failed to connect to http://localhost:29222/json/version
                     (chromic_pdf 1.14.0) lib/chromic_pdf/pdf/connection/inet.ex:74: ChromicPDF.Connection.Inet.websocket_debugger_url/1
                     (chromic_pdf 1.14.0) lib/chromic_pdf/pdf/connection/inet.ex:38: ChromicPDF.Connection.Inet.handle_init/1
                     (chromic_pdf 1.14.0) lib/chromic_pdf/pdf/connection/inet.ex:7: ChromicPDF.Connection.Inet.init/1
                     (stdlib 5.1.1) gen_server.erl:962: :gen_server.init_it/2
                     (stdlib 5.1.1) gen_server.erl:917: :gen_server.init_it/6
                     (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
     stacktrace:
       (ex_unit 1.15.7) lib/ex_unit/callbacks.ex:570: ExUnit.Callbacks.start_supervised!/2
       test/integration/inet_connection_test.exs:23: ChromicPDF.InetConnectionTest.__ex_unit_setup_0_0/1
       ChromicPDF.InetConnectionTest.__ex_unit_describe_0/1
```

### What I've found:

When looking at the actual issue, the request made via `:httpc.request` for the websocket debugger url is returning `:econnrefused`

```elixir
      url = String.to_charlist("http://#{host}:#{port}/json/version")
      headers = [{'accept', 'application/json'}]
      http_request_opts = [ssl: [verify: :verify_none]]

      case :httpc.request(:get, {url, headers}, http_request_opts, []) do # this returns the below code snippet
        {:ok, {_, _, body}} ->
          body
          |> Jason.decode!()
          |> Map.fetch!("webSocketDebuggerUrl")

        {:error, {:failed_connect, _}} ->
          raise ConnectionLostError, "failed to connect to #{url}"
      end
```

the response from `:httpc.request(:get, {url, headers}, http_request_opts, []) `

```
{:error,
 {:failed_connect,
  [{:to_address, {~c"localhost", 29224}}, {:inet, [:inet], :econnrefused}]}}
```

I've verified that it's detecting chrome from my path, and when I run `ChromicPDF.warm_up()` it returns the below

```elixir
iex(2)> ChromicPDF.warm_up()
{:ok, "<html><head></head><body></body></html>\r\n"}
```

### Other things to note
On my Mac setup, the test runs fine. It's using a pretty identical setup

- OS: Monterey 12.7.1
- Erlang: 26.1.2
- Elixir: 15.7
- Chrome: Version 120.0.6099.71 (Official Build) (x86_64)
- chromic_pdf: latest from main

the response from `:httpc.request(:get, {url, headers}, http_request_opts, []) `

```
{:ok,
 {{~c"HTTP/1.1", 200, ~c"OK"},
  [
    {~c"content-length", ~c"440"},
    {~c"content-type", ~c"application/json; charset=UTF-8"},
    {~c"content-security-policy", ~c"frame-ancestors 'none'"}
  ],
  ~c"{\n   \"Browser\": \"HeadlessChrome/120.0.6099.71\",\n   \"Protocol-Version\": \"1.3\",\n   \"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/120.0.6099.71 Safari/537.36\",\n   \"V8-Version\": \"12.0.267.8\",\n   \"WebKit-Version\": \"537.36 (@9729082fe6174c0a371fc66501f5efc5d69d3d2b)\",\n   \"webSocketDebuggerUrl\": \"ws://localhost:29222/devtools/browser/7441a413-194c-4f17-92f8-b60f656e2cda\"\n}\n"}}
```

Anyone have any ideas what might be happening, and could it be erlang 26 related potentially?

**Comment by maltoe** [comment]
Hi @joshamb 

first of all, thank you for the detailed issue description! 

`econnrefused` sounds like either the [`TestInitChrome`](https://github.com/bitcrowd/chromic_pdf/blob/732392c30f415b60c16cc291cc8fd1529c8c125e/test/integration/support/test_inet_chrome.ex#L16) failed to launch or bind to port `:29224`, or the `ChromicPDF.Connection` process inside the test fails to connect to that port due to firewall issues. I'm leaning towards the latter. You could try to manually start a chrome process like this with the `ChromeRunner` on console, and see if the port is open (`netstat` or whatever is available on Windows). Or follow the docs on ["remote" Chrome instance](https://hexdocs.pm/chromic_pdf/ChromicPDF.html#module-remote-chrome) and find out if ChromicPDF can talk to a Chrome inside a docker container.

Is this an actual bug for you? i.e. are you trying to use a remote chrome in your app?

> and could it be erlang 26 related potentially?

Anything could be related to Erlang/OTP 26, it broke sooo much :smiley: Though in this case, I am more suspicious of Windows than anything else. My uneducated guess would be that you are in fact the first person to try ChromicPDF on Windows.

**Comment by maltoe** [comment]
Hey @joshamb 

I'm going to close this for now. Feel free to reopen if it turns out to be related to ChromicPDF.
