### ISSUE TITLE
Loading external files fails when printing from in-memory HTML

### ISSUE THREAD

**Issue by Zelzahn** [bitcrowd/chromic_pdf#303]
Hey, big thanks for this library! I'm currently switching over from [elixir-pdf-generator](https://github.com/gutschilla/elixir-pdf-generator), and I'm having some difficulties loading external files (currently I only tested this locally and not on production).

For example, this image does not render: `<img src="https://localhost:8080/images/logo.svg" height="100%" width="100%" />` 
I found out that for rendering it via `chromium --headless --print-to-pdf` I had to give the ` --ignore-certificate-errors --disable-proxy-certificate-handler` arguments. So I added them to `chrome_args`, but the issue persists.

My `chromic_pdf_opts`: `[disable_scripts: false, offline: false, chrome_args: "--ignore-certificate-errors --disable-proxy-certificate-handler"]`

This is the error Chromium gives, for which I had to add those arguments:
```
[0301/135100.647427:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping mandatory platform policies because no policy file was found at: /etc/chromium/policies/managed
[0301/135100.647482:INFO:policy_logger.cc(145)] :components/policy/core/common/config_dir_policy_loader.cc(118) Skipping recommended platform policies because no policy file was found at: /etc/chromium/policies/recommended
[0301/135100.660861:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[0301/135100.683754:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0301/135100.782210:ERROR:cert_verify_proc_builtin.cc(874)] CertVerifyProcBuiltin for localhost failed:
----- Certificate i=0 (CN=Self-signed test certificate,O=Phoenix Framework) -----
ERROR: No matching issuer found
```

And this is how I render the PDF:
```
Phoenix.View.render(
        MyView,
        "pdf.html",
        layout: {LayoutView, "pdf.html"},
        conn: conn
      )
      |> Phoenix.HTML.safe_to_string()
      |> then(&ChromicPDF.print_to_pdf({:html, &1}, output: path))
```

Am I doing something wrong? Or are there any steps that I could take to better debug this?

**Comment by maltoe** [comment]
Hey @Zelzahn,

the error sure looks like Chromium isn't loading your asset due to the failed TLS peer verification. I would also expect `--ignore-certificate-errors` in `:chrome_args` to fix this, but I've never tried this and can't say why it doesn't work. Perhaps it conflicts with one of our [default command line args](https://github.com/bitcrowd/chromic_pdf/blob/main/lib/chromic_pdf/pdf/chrome_runner.ex#L108), but not sure.


Besides debugging `--ignore-certificate-errors` and making it work with ChromicPDF), here are a few options to solve your issue differently:

1. Make Chromium accept your self-signed certificate. However, Chromium uses its own certificate store instead of your OS's, and the recommended [method to add self-signed certificates](https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md) is quite cumbersome, so this path may turn out expensive given you don't gain much besides a local TLS connection.
2. Don't use a local TLS connection. For instance, you can give chromium its own (non-https) Phoenix endpoint to connect to. You should be able to reuse your existing routers + views for this (i.e. share them with your public https endpoint). Make sure to bind to `127.0.0.1` only if this is a public host.
3. Serve the assets differently, e.g. use `file:///` paths or embed them as data-uris.

Hope this helps.

malte

**Comment by Zelzahn** [comment]
Thanks for the swift reply! I'll try the second option, hopefully it'll then work :smile:
