### ISSUE TITLE
Unable to view images in rendered pdf

### ISSUE THREAD

**Issue by ibooking-anders** [bitcrowd/chromic_pdf#55]
Hey, thanks for creating this project. I like how it works almost right out of the box.

I'm in the middle of testing, and the html file I want to convert to a pdf contains a single image. 

    [content: [ "<div><img src=\"potato.png\"></div>]]
    |> ChromicPDF.Template.source_and_options()
    |> ChromicPDF.print_to_pdf(output: "lib/pdftest_web/templates/pdf_templates/potatoResult.pdf")

The potato.png file is located in the outer most phoenix directory (next to /lib, /priv, etc..) If I run that in the IEx terminal, the resulting pdf is empty. 

However, if I put some other html as input, it functions normally.

**Comment by andreasknoepfle** [comment]
Hey Anders 👋 

this is a similar issue like [this one](https://github.com/bitcrowd/chromic_pdf/issues/53). The problem here is that we render the pdf with `chrome` and `chrome` has then no idea where to look for your `potato.png`. 
This could be solved by either passing absolute `file://` URLs in the `<img>` tag, using a base64 version of the image inline (we picked this option quite successfully in the past) or getting the entire page content from a different absolute host URL (like starting a webserver that serves your html with image instead and printing the URL instead of passing a String to `chromic_pdf`).

@maltoe: As I feel like we will answer this question more often should we have a little mini section in the main README that outlines the options? We could even have some base64 helpers to make it easier to use. 

Cheers
Andi

**Comment by maltoe** [comment]
@andreasknoepfle 👍  i agree, the README seems to be lacking a bit in this area. Also, the `Template` uses the `{:html, ...}` way of setting the DOM content by default, and I fear the consequences are not obvious for users; so we should improve the docs for `Template` as well. Though I'm happy that it seems to be useful, it took me quite some time to figure out the right CSS to get Chrome to print the headers & footers right, etc.

**Comment by ibooking-anders** [comment]
Wooh, thank you Andi 💯  The inline base64 option worked like a charm. Thank you so much for the fast reply.
