### ISSUE TITLE
Generating Large PDFs causes Timeout

### ISSUE THREAD

**Issue by dabaer** [bitcrowd/chromic_pdf#83]
Hello,

I'm attempting to generate a large pdf (100 pages) however the GenServer times out after only 5 (!) seconds. Is there a way to override this? I don't see a supervisor option to do so, and I can't seem to track down the timeout in the source.

Regards,
Dakora

**Comment by maltoe** [comment]
Hey @dabaer,

no, sorry, the timeout is not configurable yet, or rather is not configurable anymore since I switched to `nimble_pool` a while ago. But we can make it be configurable again.

I *think* the only `GenServer.call/3` that needs a timeout set is in `Channel`:

https://github.com/bitcrowd/chromic_pdf/blob/b703d05420f65397b904c7d0779ff19127e79bad/lib/chromic_pdf/pdf/browser/channel.ex#L20-L22

[`NimblePool.checkout!/4`](https://hexdocs.pm/nimble_pool/NimblePool.html#checkout!/4) also has a timeout option (same default according to the docs), which I think only applies to the checkout itself (retrieving the resource from the pool), so I suppose this should use a different timeout value (and option). Regardless, the `SessionPool` is a good place to extract the value from the option list and pass it to the `Channel`. See `pool_size/1` as well.

https://github.com/bitcrowd/chromic_pdf/blob/b703d05420f65397b904c7d0779ff19127e79bad/lib/chromic_pdf/pdf/browser/session_pool.ex#L50-L55

I *think* this should be enough. Maybe with these ideas you're willing to submit a PR? 😍  Otherwise I'll create a patch later, maybe not today but probably this week.

cheers,
malte

**Comment by dabaer** [comment]
Thank you, I just wasn't sure if I was missing an option somewhere. For now I limited the pages being generated and they seem to do so well within the window, so I don't mind waiting for this patch.

**Comment by maltoe** [comment]
@dabaer patch is merged to `main`, can you give it a shot?

**Comment by dabaer** [comment]
Apologies for the delay, yesterday was issue crunch day. This does the trick exactly, thanks!
